# Generated by Django 4.2.29 on 2026-04-02 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parties", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("lent_out", "Lent Out"),
                            ("borrowed_in", "Borrowed In"),
                        ],
                        max_length=20,
                    ),
                ),
                ("borrow_date", models.DateField()),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("partially_returned", "Partially Returned"),
                            ("returned", "Returned"),
                        ],
                        default="open",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrows",
                        to="parties.party",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-borrow_date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="BorrowItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_borrowed",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "quantity_returned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "borrow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="borrows.borrow",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrow_items",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
